import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Notification from "@/components/Notification";
import ReduxProvider from "@/redux/provider";
// import GlobalState from "@/context/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Asndaniel PIZZ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <GlobalState> */}
        <ReduxProvider>
          <Navbar />
          {children}
          <Footer />
        </ReduxProvider>
        {/* </GlobalState> */}
      </body>
    </html>
  );
}
